name: Build Corsika8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3 python3-pip cmake g++ gfortran git doxygen graphviz \
            libboost-all-dev libcli11-dev libeigen3-dev libspdlog-dev libfmt-dev libyaml-cpp-dev \
            catch2 zlib1g-dev ca-certificates lsb-release wget
        wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt install -y ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt update -y
        sudo apt install -y -V libarrow-dev libparquet-dev

  - name Install Cubic Interpolation
    shell: bash
    run: |
      wget https://github.com/tudo-astroparticlephysics/cubic_interpolation/archive/refs/tags/v0.1.5.tar.gz
      tar zxf cubic_interpolation-0.1.5.tar.gz
      cd cubic_interpolation
      mkdir build
      cd build
      cmake .. -DCMAKE_BUILD_TYPE=Release
      make -j4
      make install

  - name Install PROPOSAL
    shell: bash
    run: |
      wget https://github.com/tudo-astroparticlephysics/PROPOSAL/archive/refs/tags/7.6.2.tar.gz
      tar zxf PROPOSAL-7.6.2.tar.gz
      cd PROPOSAL
      mkdir build
      cd build
      cmake .. -DCMAKE_BUILD_TYPE=Release
      make -j4
      make install

